### ISSUE TITLE
Let external plugins optionally resolve with core deps

### ISSUE THREAD

**Issue by sormuras** [forax/pro#36]
The [three `API` lines](https://github.com/forax/pro/blob/master/src/main/java/com.github.forax.pro.bootstrap/com/github/forax/pro/bootstrap/Bootstrap.java#L89) should not be necessary. The three modules are already present at `./deps`.

How do I configure the "resolver" to use the `./deps` folder -- or would that contradict the notion of being an **external** plugin?

**Comment by forax** [comment]
it should already works because of https://github.com/forax/pro/blob/master/src/main/java/com.github.forax.pro.bootstrap/com/github/forax/pro/bootstrap/Bootstrap.java#L112 ?

**Comment by forax** [comment]
Ok, got it,
the problem is how the resolver works, it first finds the dependencies transitively and at that point, it doesn't check that the dependencies may already exists in another directory deps.

The problem is that the jar already downloaded do not stores they Maven (central) artifact id if they are not created by Maven.

A workaround is to remove the downloaded jars in plugin/tester/deps after being downloaded

**Comment by sormuras** [comment]
Methinks, this issue was resolved some time ago. Correct?

**Comment by forax** [comment]
yes !
