### ISSUE TITLE
Extract and set version in module fixing process

### ISSUE THREAD

**Issue by sormuras** [forax/pro#38]
The **modulefixer** should extract the (raw) version string from the plain JAR it processes and set the extracted version into the generated module.

Sources of version strings:

- Extract META-INF manifest attribute `Implementation-Version` value, if available.
- JAR file name convention used by Maven: `<groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>`

**Comment by forax** [comment]
I believe the former is doable but the later requires to have the Maven information inside the jar
There is no from the repository at the time the module-fixer is executed because the jar is downloaded by the resolver before.
But maybe, you are thinking about a specific file which is inserted into the jar if it is built with Maven ?

**Comment by sormuras** [comment]
> But maybe, you are thinking about a specific file which is inserted into the jar if it is built with Maven ?

Mh, no. There's none I know of.

For me (JUnit) it would suffice if a manifest attribute like `Implementation-Version` is extracted and used by the fixer.

**Comment by forax** [comment]
fixed in d5c271724dbc2f413d4390f0cd78d7462a0c2aab
